version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - prueba-network

  backend:
    container_name: backend
    build:
      context: docker/php
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - database
    networks:
      - prueba-network

  database:
    container_name: database
    image: mariadb:10.7.8
    environment:
      MYSQL_DATABASE: "prueba-db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - prueba-db:/var/lib/mysql
    networks:
      - prueba-network

volumes:
  prueba-db:

networks:
  prueba-network:
    external: true
